name: Docker tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  parallel:
    uses: ./.github/workflows/dockertests.yml
    with:
      command-json-array: >
        [
        "make pg_integration_test"
        ]
